INSERT INTO  USER (EMAIL,NAME,PASSWORD) VALUES ('vitor@gmail.com','vitor','$2a$12$M0MZT.cs2NfePHC4ZIfEpukYtY2rb1a4RtBZTeqFH5yO7H8rRPVYO');
INSERT INTO  USER (EMAIL,NAME,PASSWORD) VALUES ('rodrigo@gmail.com','rodrigo','$2a$12$M0MZT.cs2NfePHC4ZIfEpukYtY2rb1a4RtBZTeqFH5yO7H8rRPVYO');
INSERT INTO  USER (EMAIL,NAME,PASSWORD) VALUES ('admin@gmail.com','admin','$2a$12$M0MZT.cs2NfePHC4ZIfEpukYtY2rb1a4RtBZTeqFH5yO7H8rRPVYO');

INSERT INTO ROLE (AUTHORITY) VALUES ('ROLE_ADMIN');

INSERT INTO  USER_ROLE (user_id,role_id) VALUES('1','1');
INSERT INTO  USER_ROLE (user_id,role_id) VALUES('2','1');
INSERT INTO  USER_ROLE (user_id,role_id) VALUES('3','1');

